
# Server port settings
server:
  port: 9300

spring:
  application:
    name: templateBatchSAMWeb
  mvc:
    view:
      prefix: /WEB-INF/jsp/egovframework/example/
      suffix: .jsp

# Overwrite the bins created from the Spring Framework 5.* - When you try to register bins with the same name - BeanDefinitionOverrideException occurs, setting that eliminates this.
  main:
    allow-bean-definition-overriding: true

  batch:
    job:
      enabled: false

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true

logging:
  file:
    name: /home/god/my/log/my.log
  level:
    root: "error"
    com.springboot.main: "debug"
    egovframework: "debug"
    god: "debug"
    org.hibernate: "error"
  logback:
    rollingpolicy:
      file-name-pattern: my.log.%d{yyyy-MM-dd}.%i.gz
