/* 롤정보 */
INSERT INTO COMTNROLEINFO (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE) VALUES('ROLE_ANONYMOUS-web-000001', '공공데이터포털 API 롤', '/data/api/.*', '공공데이터포털 API 허용을 위한 롤', 'url', '0', SYSDATE());

/* 권한롤관계 */
INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT) VALUES ('ROLE_ANONYMOUS', 'ROLE_ANONYMOUS-web-000001', SYSDATE());
