INSERT INTO BATCH_STEP_EXECUTION_SEQ values(0,0);

INSERT INTO BATCH_JOB_EXECUTION_SEQ values(0,0);

INSERT INTO BATCH_JOB_SEQ values(0,0);

INSERT INTO CUSTOMER (ID, VERSION, NAME, CREDIT) VALUES (1, 0, 'customer1', 100050);
INSERT INTO CUSTOMER (ID, VERSION, NAME, CREDIT) VALUES (2, 0, 'customer2', 100050);
INSERT INTO CUSTOMER (ID, VERSION, NAME, CREDIT) VALUES (3, 0, 'customer3', 100050);
INSERT INTO CUSTOMER (ID, VERSION, NAME, CREDIT) VALUES (4, 0, 'customer4', 100050);